apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      args:
        - --context=$(workspaces.source.path)/apps
        - --dockerfile=$(workspaces.source.path)/apps/Dockerfile
        - --destination=$(params.IMAGE)
