apiVersion: v1
kind: Service
metadata:
  name: demo-devops-service
  namespace: demo-devops
spec:
  selector:
    app: demo-devops-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
