apiVersion: v1
kind: Service
metadata:
  name: gitops-eks-service
  namespace: default
spec:
  selector:
    app: gitops-eks-app
  ports:
    - protocol: TCP
      port: 80         # Puerto externo
      targetPort: 3000 # Puerto donde corre Node.js
  type: LoadBalancer
