apiVersion: v1
kind: Service
metadata:
  name: gitops-eks-service
  namespace: default
  labels:
    app: gitops-eks-app
spec:
  selector:
    app: gitops-eks-app
  ports:
    - name: http          # ⬅️ IMPORTANTE para Prometheus
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
